first_name: Brandon
last_name: Moffitt
email: brandon.james.moffitt@gmail.com
phone: 860-608-8952
job_url: https://ats.rippling.com/rippling/jobs/bda12f6a-6afc-45af-8e6a-b0056facf15c
resume_path: Brandon_Moffitt.pdf
cover_letter_path: Brandon_Moffitt_CoverLetter.pdf
gender: male
age: 35
race: white
are_you_disabled: no
are_you_veteran: no
are_you_hispanic_or_latino: no
location: San Francisco, CA
experience: 10 years
education: Bachelor's Degree
current_company: Arcanium
linkedin_link: https://www.linkedin.com/in/brandon-moffitt/
github_link: https://github.com/bmoffitt1990
